/**
 * Metas propuestas por seo-web y aprobadas por Diego (05-10-2026). Clave: pathname.
 * Sustituyen al title (sin sufijo de marca) y a la description que pasa cada página.
 */
export const metas: Record<string, { title?: string; description?: string }> = {
  "/": {"description": "Consultora tecnológica para pymes en Barcelona. Diagnóstico gratuito, transformación operativa con IA, seguridad de asistentes y partner tecnológico."},
  "/servicios/": {"title": "Servicios de IA para pymes", "description": "Diagnóstico gratuito, transformación operativa con IA, partner tecnológico y auditoría de seguridad de asistentes para pymes."},
  "/servicios/transformacion/": {"description": "Implantación, integración con tus sistemas, automatización y formación de tu equipo. De cuatro a doce semanas, empezando por un piloto."},
  "/servicios/partner/": {"description": "Revisión de propuestas de proveedores, interlocución técnica, hoja de ruta trimestral y auditoría de software. Tres paquetes."},
  "/licita/": {"title": "Licita: motor de licitaciones", "description": "Licita rastrea licitaciones de las 17 comunidades autónomas y de Europa, y resume cada pliego en una ficha con cierre, importe y solvencia."},
  "/productos/": {"description": "LeakAI, nuestro producto propio de ciberseguridad de IA, y el portfolio de nuestro grupo tecnológico: compliance, atención al cliente y educación."},
  "/productos/leakai/": {"title": "LeakAI: auditoría de seguridad de chatbots"},
  "/productos/regulia/": {"title": "Regulia: compliance europeo para pymes"},
  "/productos/swarmix/": {"title": "Swarmix: outreach con IA"},
  "/productos/contablia/": {"title": "Contablia: agentes de IA para autónomos"},
  "/productos/contestia/": {"title": "Contestia: recepcionista virtual por WhatsApp"},
  "/productos/instantexam/": {"title": "InstantExam: exámenes con IA"},
  "/productos/scoreflow/": {"title": "ScoreFlow: score de calidad para AI coding"},
  "/sectores/": {"title": "Sectores: IA para seis verticales"},
  "/sectores/administracion/": {"description": "Diagnóstico de procesos, sede electrónica conversacional, clasificación documental y análisis de expedientes. Cumplimiento ENS, datos en la UE."},
  "/sectores/clinicas/": {"description": "Recepcionista virtual por WhatsApp, agenda inteligente y notas clínicas automáticas. Tu equipo se centra en los pacientes."},
  "/sectores/industria/": {"description": "Predicción de averías, presupuestos automáticos y QA visual con cámara. Para talleres y plantas que quieren reducir tiempo muerto."},
  "/contacto/": {"title": "Contacto y diagnóstico gratuito"},
  "/casos-de-uso/": {"description": "41 capacidades de IA aplicada que hemos construido y puesto en producción. Filtra por familia, sector y tecnología."},
  "/estudio-asistentes-ia/": {"title": "Estudio: asistentes de IA en webs españolas", "description": "Rastreamos 391 webs españolas y encontramos 29 asistentes con IA respondiendo en abierto. Datos propios, septiembre de 2026."},
  "/historias-de-exito/clinicas-dentales-barcelona/": {"title": "Tres clínicas dentales: 38% menos ausencias"},
  "/historias-de-exito/despacho-mercantil/": {"title": "Despacho mercantil: 20h liberadas por socio"},
  "/historias-de-exito/distribuidora-industrial/": {"title": "Distribuidora industrial: 2h por comercial al día"},
  "/politica-cookies/": {"description": "Este sitio no instala cookies propias. La analítica es anónima y sin cookies; el calendario de Google solo se carga si pulsas para verlo."},
  "/ca/": {"description": "Consultora tecnològica per a pimes a Barcelona. Diagnòstic gratuït, transformació operativa amb IA, seguretat d'assistents i soci tecnològic."},
  "/ca/servicios/": {"title": "Serveis d'IA per a pimes", "description": "Diagnòstic gratuït, transformació operativa amb IA, soci tecnològic i auditoria de seguretat d'assistents per a pimes."},
  "/ca/servicios/transformacion/": {"description": "Implantació, integració amb els teus sistemes, automatització i formació del teu equip. De quatre a dotze setmanes, amb un pilot."},
  "/ca/servicios/partner/": {"description": "Revisió de propostes de proveïdors, interlocució tècnica, full de ruta trimestral i auditoria de programari. Tres paquets."},
  "/ca/licita/": {"title": "Licita: motor de licitacions", "description": "Licita rastreja licitacions de les 17 comunitats autònomes i d'Europa, i resumeix cada plec en una fitxa amb tancament, import i solvència."},
  "/ca/productos/": {"description": "LeakAI, el nostre producte propi de ciberseguretat d'IA, i el portfolio del nostre grup tecnològic: compliance, atenció al client i educació."},
  "/ca/productos/leakai/": {"title": "LeakAI: auditoria de seguretat de xatbots"},
  "/ca/productos/regulia/": {"title": "Regulia: compliance europeu per a pimes"},
  "/ca/productos/swarmix/": {"title": "Swarmix: outreach amb IA"},
  "/ca/productos/contablia/": {"title": "Contablia: agents d'IA per a autònoms"},
  "/ca/productos/contestia/": {"title": "Contestia: recepcionista virtual per WhatsApp"},
  "/ca/productos/instantexam/": {"title": "InstantExam: exàmens amb IA"},
  "/ca/productos/scoreflow/": {"title": "ScoreFlow: score de qualitat per a AI coding"},
  "/ca/sectores/": {"title": "Sectors: IA per a sis verticals"},
  "/ca/sectores/administracion/": {"description": "Diagnòstic de processos, seu electrònica conversacional, classificació documental i anàlisi d'expedients. Compliment ENS, dades a la UE."},
  "/ca/sectores/clinicas/": {"description": "Recepcionista virtual per WhatsApp, agenda intel·ligent i notes clíniques automàtiques. El teu equip es centra en els pacients."},
  "/ca/contacto/": {"title": "Contacte i diagnòstic gratuït"},
  "/ca/casos-de-uso/": {"description": "41 capacitats d'IA aplicada que hem construït i posat en producció. Filtra per família, sector i tecnologia."},
  "/ca/estudio-asistentes-ia/": {"title": "Estudi: assistents d'IA a webs espanyoles", "description": "Vam rastrejar 391 webs espanyoles i vam trobar 29 assistents amb IA responent en obert. Dades pròpies, setembre de 2026."},
  "/ca/historias-de-exito/clinicas-dentales-barcelona/": {"title": "Tres clíniques dentals: 38% menys absències"},
  "/ca/historias-de-exito/despacho-mercantil/": {"title": "Despatx mercantil: 20h alliberades per soci"},
  "/ca/historias-de-exito/distribuidora-industrial/": {"title": "Distribuïdora industrial: 2h per comercial al dia"},
  "/ca/politica-cookies/": {"title": "Política de cookies del lloc web"},
};
